name: "Java"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        java-version: [17,21,23]

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4

      - uses: actions.setup-java@v4
        with:
          distribution: "oracle"
          java-version: ${{ matrix.java-version }}
          cache: "gradle"

      - name: "Build project"
        run: ./project/gradlew build

      - name: "Create distribution"
        run: ./project/gradlew distZip

      - uses: actions/upload-artifact@v4
        with:
          path: build/distributions/SSH-Fridge-Contents-Tracker.zip
          name: SSH-Fridge-Contents-Tracker-java-${{ matrix.java-version }}
