services:

  postgres:
    image: postgres:latest
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=group
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=ssh

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
