package com.sshgroup.ssh_fridge_contents_tracker;

import com.sshgroup.ssh_fridge_contents_tracker.DatabaseAccess;
import com.sshgroup.ssh_fridge_contents_tracker.Ingredients;
import com.sshgroup.ssh_fridge_contents_tracker.Recipe;
import com.sshgroup.ssh_fridge_contents_tracker.Recipe_Ingredients;
import jakarta.transaction.Transactional;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Scanner;

public class RecipeCreator {
    public static void createRecipe() {
        SessionFactory sessionFactory = DatabaseAccess.setup();

        try (Scanner scanner = new Scanner(System.in)) {
            System.out.print("Enter the recipe name: ");
            String recipeName = scanner.nextLine();

            System.out.print("Enter recipe instructions: ");
            String recipeInstructions = scanner.nextLine();

            System.out.print("Enter the number of people it serves / number of servings it has: ");
            int num_servings = Integer.parseInt(scanner.nextLine());

            List<String> ingredientNames = new ArrayList<>();
            List<Double> amountNeeded = new ArrayList<>();
            List<String> categories = new ArrayList<>();

            while (true) {
                System.out.print("Enter ingredient name (or done): ");
                String temp = scanner.nextLine();
                if ("done".equals(temp)) {
                    break;
                }
                ingredientNames.add(temp);

                System.out.print("Enter amount required: ");
                double amount = Double.parseDouble(scanner.nextLine());
                amountNeeded.add(amount);
            }

            while (true) {
                System.out.print("Enter any categories that apply to the recipe (or done): ");
                String temp = scanner.nextLine();
                if ("done".equals(temp)) {
                    break;
                }
                categories.add(temp);
            }

            try (Session session = sessionFactory.openSession()) {
                session.beginTransaction();

                Recipe recipe = new Recipe();
                recipe.setRecipe_name(recipeName);
                recipe.setRecipe_instruction(recipeInstructions);
                recipe.setNumber_servings(num_servings);
                session.persist(recipe);

                for (int i = 0; i < ingredientNames.size(); i++) {
                    String ingredientName = ingredientNames.get(i);
                    double quantityNeeded = amountNeeded.get(i);

                    Ingredients ingredient = findIngredient(session, ingredientName);
                    if (ingredient == null) {
                        ingredient = new Ingredients();
                        ingredient.setIngredients(ingredientName);
                        ingredient.setQuantity(quantityNeeded);
                        session.persist(ingredient);
                    } else {
                        ingredient.setQuantity(ingredient.getQuantity() + quantityNeeded);
                    }

                    Recipe_Ingredients recipeIngredients = new Recipe_Ingredients();
                    recipeIngredients.setRecipe_id(recipe);
                    recipeIngredients.setIngredients_id(ingredient);
                    recipeIngredients.setQuantity_needed(quantityNeeded);
                    session.persist(recipeIngredients);
                }
                for (int i = 0; i < categories.size(); i++) {
                    String category = categories.get(i);

                    Category category1 = findCategory(session, category);
                    if (category1 == null) {
                        category1 = new Category();
                        category1.setCategory_name(category);
                        session.persist(category1);
                    }

                    Recipe_Category recipeCategories = new Recipe_Category();
                    recipeCategories.setRecipe_id(recipe);
                    recipeCategories.setCategory_id(category1);
                    session.persist(recipeCategories);
                }

                session.getTransaction().commit();
            }
        }
    }

    /**
     * Gets the {@link com.sshgroup.ssh_fridge_contents_tracker.Ingredients} object from the database for a specified ingredient name
     * @param session the session object generated by the session factory for hibernate
     * @param name the name of ingredient you are looking to get
     * @return null on error, or the {@link com.sshgroup.ssh_fridge_contents_tracker.Ingredients} object that you were looking for
     */
    static Ingredients findIngredient(Session session, String name) {
        return session.createQuery("FROM Ingredients WHERE ingredients_name = :name", Ingredients.class)
                .setParameter("name", name)
                .uniqueResult();
    }

    /**
     * Gets the {@link com.sshgroup.ssh_fridge_contents_tracker.Recipe} from the database for a specified recipe name
     * @param session the session object generated by the session factory for hibernate
     * @param name the name of recipe you are looking to get
     * @return null on error, or the {@link com.sshgroup.ssh_fridge_contents_tracker.Recipe} object that you were looking for
     */
    public static List<Recipe> findRecipe(Session session, String name) {
        if (session == null || name == null || name.isEmpty()) {
            return null;
        }
        return session.createQuery("FROM Recipe WHERE recipe_name = :name", Recipe.class)
                .setParameter("name", name)
                .getResultList();
    }

    /**
     * Gets the {@link com.sshgroup.ssh_fridge_contents_tracker.Category} from the database for a specified category name
     * @param session the session object generated by the session factory for hibernate
     * @param name the name of category you are looking to get
     * @return null on error, or the {@link com.sshgroup.ssh_fridge_contents_tracker.Category} object that you were looking for
     */
    public static Category findCategory(Session session, String name) {
        if (session == null || name == null || name.isEmpty()) {
            return null;
        }
        return session.createQuery("FROM Category WHERE category_name = :name", Category.class)
                .setParameter("name", name)
                .uniqueResult();
    }

    /**
     * adds a recipe to the database
     * @param recipeName the name of this recipe
     * @param recipeInstructions the instructions in creating this recipe
     * @return null on error or the {@link com.sshgroup.ssh_fridge_contents_tracker.Recipe} object created and stored in the database
     */
    public static Recipe addRecipe(String recipeName, String recipeInstructions, int number_servings) {
        if (recipeName == null || recipeInstructions == null || recipeName.isEmpty() || recipeInstructions.isEmpty()) {
            return null;
        }
        SessionFactory sessionFactory = DatabaseAccess.setup();
        try (Session session = sessionFactory.openSession()) {
            session.beginTransaction();
            Recipe recipe = new Recipe();
            recipe.setRecipe_name(recipeName);
            recipe.setRecipe_instruction(recipeInstructions);
            recipe.setNumber_servings(number_servings);
            session.persist(recipe);
            session.getTransaction().commit();
            return recipe;
        }
    }

    /**
     * adds an {@link com.sshgroup.ssh_fridge_contents_tracker.Ingredients} to the database
     * @param ingredientName the string name of the ingredient
     * @param quantityAvailiable the quantity of the ingredient availiabe
     * @return null on error, otherwise the {@link com.sshgroup.ssh_fridge_contents_tracker.Ingredients} object
     */
    public static Ingredients addIngredient(String ingredientName, double quantityAvailiable) {
        if (ingredientName == null || ingredientName.isEmpty()) {
            return null;
        }
        SessionFactory sessionFactory = DatabaseAccess.setup();
        try (Session session = sessionFactory.openSession()) {
            session.beginTransaction();
            Ingredients ingredient = findIngredient(session, ingredientName);
            if (ingredient == null) {
                ingredient = new Ingredients();
                ingredient.setIngredients(ingredientName);
                ingredient.setQuantity(quantityAvailiable);
                //ingredient.setCost_per_kg(0);
            }
            else {
                ingredient.setQuantity(ingredient.getQuantity() + quantityAvailiable);
            }
            session.persist(ingredient);
            session.getTransaction().commit();
            return ingredient;
        }
    }

    /**
     * adds a {@link com.sshgroup.ssh_fridge_contents_tracker.Category} to the database
     * @param categoryName the string name of the category
     * @return null on error or the {@link com.sshgroup.ssh_fridge_contents_tracker.Category} object
     */
    public static Category addCategory(String categoryName) {
        if (categoryName == null || categoryName.isEmpty()) {
            return null;
        }
        SessionFactory sessionFactory = DatabaseAccess.setup();
        try (Session session = sessionFactory.openSession()) {
            session.beginTransaction();
            Category category = findCategory(session, categoryName);
            if (category == null) {
                category = new Category();
                category.setCategory_name(categoryName);
                //ingredient.setCost_per_kg(0);
            }
            session.persist(category);
            session.getTransaction().commit();
            return category;
        }
    }

    /**
     * Creates a many-to-many relationship between {@link com.sshgroup.ssh_fridge_contents_tracker.Recipe}s and {@link com.sshgroup.ssh_fridge_contents_tracker.Ingredients}
     * @param recipe the {@link com.sshgroup.ssh_fridge_contents_tracker.Recipe} object / record
     * @param ingredient the {@link com.sshgroup.ssh_fridge_contents_tracker.Ingredients} object /record
     * @param quantityNeeded the quantity of the ingredient needed for this recipe
     * @return null on error, or otherwise returns the {@link com.sshgroup.ssh_fridge_contents_tracker.Recipe_Ingredients} object
     */
    public static Recipe_Ingredients addLinkBetweenIngredientAndRecipe(Recipe recipe, Ingredients ingredient, double quantityNeeded) {
        if (recipe == null || ingredient == null) {
            return null;
        }
        SessionFactory sessionFactory = DatabaseAccess.setup();
        try (Session session = sessionFactory.openSession()) {
            session.beginTransaction();
            Recipe_Ingredients recipeIngredients = new Recipe_Ingredients();
            recipeIngredients.setRecipe_id(recipe);
            recipeIngredients.setIngredients_id(ingredient);
            recipeIngredients.setQuantity_needed(quantityNeeded);
            session.persist(recipeIngredients);
            session.getTransaction().commit();
            return recipeIngredients;
        }
    }

    /**
     * Creates a many-to-many relationship between {@link com.sshgroup.ssh_fridge_contents_tracker.Recipe}s and {@link com.sshgroup.ssh_fridge_contents_tracker.Category}s
     * @param recipe the {@link com.sshgroup.ssh_fridge_contents_tracker.Recipe} object / record
     * @param category the {@link com.sshgroup.ssh_fridge_contents_tracker.Category} object /record
     * @return null on error, or otherwise returns the {@link com.sshgroup.ssh_fridge_contents_tracker.Recipe_Category} object
     */
    public static Recipe_Category addLinkBetweenCategoryAndRecipe(Recipe recipe, Category category) {
        if (recipe == null || category == null) {
            return null;
        }
        SessionFactory sessionFactory = DatabaseAccess.setup();
        try (Session session = sessionFactory.openSession()) {
            session.beginTransaction();
            Recipe_Category recipeCat = new Recipe_Category();
            recipeCat.setRecipe_id(recipe);
            recipeCat.setCategory_id(category);
            session.persist(recipeCat);
            session.getTransaction().commit();
            return recipeCat;
        }
    }
}
