name: "Docker"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    permissions:
      packages: write
      contents: read

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: Configure Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/harryz8/SEPP-SSH-Project
          tags: |
            type=sha
            type=raw,value=latest,enable=true

      - name: Authenticate
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set up docker build
        uses: docker/setup-buildx-action@v3
        with:
          context: project
      
      - name: Build and upload image
        uses: docker/build-push-action@v6
        with:
          context: project
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
