name: "Java"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        java-version: [17,21,23]

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: ${{ matrix.java-version }}
          cache: "gradle"

      - name: "Build project"
        working-directory: ./project
        run: ./gradlew build

  publish-job:
    runs-on: "ubuntu-latest"
    needs: build
    
    strategy:
      matrix:
        java-version: [17,21,23]

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: ${{ matrix.java-version }}
          cache: "gradle"
      
      - name: "Create distribution"
        working-directory: ./project
        run: ./gradlew distZip

      - uses: actions/upload-artifact@v4
        with:
          path: project/build/distributions/SSH_Fridge_Contents_Tracker-1.0.zip
          name: SSH-Fridge-Contents-Tracker-java-${{ matrix.java-version }}
