name: "Java"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        java-version: [17,21,23]

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: ${{ matrix.java-version }}
          cache: "gradle"

      - name: "Build project"
        working-directory: ./project
        run: ./gradlew build

  publish-job:
    runs-on: "ubuntu-latest"
    needs: build
    
    strategy:
      matrix:
        java-version: [17,21,23]

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: ${{ matrix.java-version }}
          cache: "gradle"
      
      - name: "Create distribution"
        working-directory: ./project
        run: ./gradlew distZip

      - uses: actions/upload-artifact@v4
        with:
          path: project/build/distributions/SSH_Fridge_Contents_Tracker-1.0.zip
          name: SSH-Fridge-Contents-Tracker-java-${{ matrix.java-version }}

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: "oracle"
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      - name: Publish the package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}