name: Publish project as a package to GitHub packages
on:
    release:
    types: [created]
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-java@v4
            with:
                java-version: '21'
                distribution: "oracle"
          - name: Setup gradle
            uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
          - name: Publish the package
            run: ./gradlew publish
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}